name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  logon:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
    # You may pin to the exact commit or the version.
   # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
        #registry: # optional
    # Username used to log against the Docker registry
        username: slmagus
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.dockerhub_token }}
    # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false # optional, default is auto
    # Log out from the Docker registry at the end of a job
        #logout: # optional, default is true
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: list
      run: cd .. && ls -lah && pwd
    - name: Build contractbuilding image
      run: docker build --target contractbuilding --tag slmagus/contractbuilding:latest .
    - name: Push contractbuilding image
      run: docker push slmagus/ontractbuilding:latest
    - name: Build contractui image
      run: docker build --target contractui --tag slmagus/contractui:latest .
    - name: Push contractui image
      run: docker push slmagus/contractui:latest
    - name: Build substatenode image
      run: docker build --target substratenode --tag slmagus/substratenode:latest .
    - name: Push substatenode image
      run: docker push slmagus/substratenode:latest